### PR TITLE
Update for version 1.7.0

### PR DESCRIPTION
**Pull request by felix-cw**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by felix-cw** [comment]
@conda-forge-admin, please rerender

**Comment by MarcoGorelli** [comment]
thanks @felix-cw !

**Comment by felix-cw** [comment]
@MarcoGorelli Good morning! Thanks a lot for reviewing and merging! It looks like the build didn't work after merging though due to the conda forge issues yesterday. Are you able to get it to retry?

**Comment by MarcoGorelli** [comment]
morning! I don't know how to do that, could you please advise?

I'm kind of tempted to just get rid of the conda-forge

**Comment by MarcoGorelli** [comment]
@conda-forge-admin, please rerender

**Comment by felix-cw** [comment]
This might work:
@conda-forge-admin, please restart ci

**Comment by MarcoGorelli** [comment]
did this work https://github.com/conda-forge/nbqa-feedstock/pull/50 ?

**Comment by felix-cw** [comment]
Yes it worked. I can see the new version in anaconda.org.  I'm really sorry this has been such a bother.

**Comment by MarcoGorelli** [comment]
😄 no worries, this was easier than expected, I should stop complaining so much

anyway, looks like there's still an issue, so I may need another release soon https://github.com/charliermarsh/ruff/issues/3744

**Pull request merged**
