### PR TITLE
Update version and sha to pypi version 0.4.0

### PR DESCRIPTION
**Pull request by s-weigand**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by s-weigand** [comment]
@conda-forge-admin, please rerender

**Comment by MarcoGorelli** [comment]
does this mean it's good to merge?

**Comment by s-weigand** [comment]
Yeah just let the CI finish and it is good to merge ^^

**Comment by s-weigand** [comment]
Hmm didn't rerender yet

**Comment by s-weigand** [comment]
@conda-forge-admin, please rerender

**Comment by s-weigand** [comment]
Ups did miss the bots comment 🤣 
So it should be fine

**Comment by MarcoGorelli** [comment]
cool, thanks for your help here!

**Pull request merged**
