### PR TITLE
Should depend on importlib-metadata package

### PR DESCRIPTION
**Pull request by jamesmyatt**
importlib_metadata is an alias for importlib-metadata
See https://github.com/conda-forge/importlib_metadata-feedstock/blob/master/recipe/meta.yaml

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jamesmyatt** [comment]
@conda-forge-admin, please rerender

**Comment by MarcoGorelli** [comment]
What's wrong with using the alias?

**Review by MarcoGorelli — CHANGES_REQUESTED** [review]
could you also comment on why the other changes are necessary please?

**Comment by s-weigand** [comment]
I guess the difference is just that there is an additional package, with the pinned version of the actual package 🤷‍♀️

As for the other changes, they were made by the conda-forge bot when posting [this comment](https://github.com/conda-forge/nbqa-feedstock/pull/32#issuecomment-968919932).
Basically, it is the similar to `pre-commit autoupdate`, just for the conda forge build scripts.

**Comment by jamesmyatt** [comment]
@MarcoGorelli, it's just an extra unnecessary package. It's worth using the core package in case the alias is ever removed or deprecated. Although it's likely that that support for py<38 will end first making the importlib-metadata package redundant.

And as @s-weigand, the other changes are from @conda-forge-linter rerendering the feedstock.

**Comment by jamesmyatt** [comment]
You also have this comment, which I think is wrong.

```
# Only required for [py<38] but always include so this can be noarch: python
```

As I understand it, "noarch" is about saying that the same binaries can be used across different platforms like linux64 and win64, rather than across different python versions. I think that you can use the python version selectors and keep noarch.

I can try it with the selector included, which simplifies the dependencies (potentially).

**Comment by s-weigand** [comment]
Back then when I created the recipe I asked on `conda-forge` `gitter` if you can have the python version selector and they said that there sadly is no way to have our cake and also eat it. If you want to specify python versions you can **NOT** be `noarch`.

Guess this has some historical reasons, like redirecting the build and lookup functionality 🤷‍♀️

If that got fixed by now it would be great ❤️

**Comment by MarcoGorelli** [comment]
Sure, happy to have this fixed, thanks!

**Comment by jamesmyatt** [comment]
OK. Looks like I was wrong about the selectors. But I'll leave the ">=1.4" so that it matches the version in Python 3.8 according to https://pypi.org/project/importlib-metadata/.

**Comment by jamesmyatt** [comment]
noarch packages can't have selectors

**Comment by MarcoGorelli** [comment]
Thanks @jamesmyatt

**Pull request merged**
